name: Sync to gitea

on:
  push:
    branches: [master]

jobs:
  sync:
    name: Sync to gitea
    runs-on: ubuntu-latest
    steps:
      - name: Sync to gitea
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEA_RSA_PRIVATE_KEY}}
        with:
          source-repo: git@github.com:botyubao/doc.git
          destination-repo: git@gitea.pipichen.com@21568:botyubao/doc.git
